<?php
 $quer = "SELECT ID_VERSION, TITRE , DATE , CATEGORIE , IMAGE , CAPACITE - COUNT(NUM_BILLET) AS 'DISPONIBLE' FROM BILLET INNER JOIN FACTURE USING(NUM_FACTURE) RIGHT JOIN VERSION USING(ID_VERSION) INNER JOIN EVENEMENT USING(ID_EVENT) INNER JOIN SALLE USING (NUM_SALLE) GROUP BY ID_VERSION HAVING VERSION.DATE > now()";
 $sql = $conn->prepare($quer);
 $sql->execute();
 $allEvents = $sql->fetchALL(PDO::FETCH_ASSOC);

 $another = "SELECT ID_VERSION, TITRE , DATE , CATEGORIE , IMAGE , CAPACITE - COUNT(NUM_BILLET) AS 'DISPONIBLE' FROM BILLET INNER JOIN FACTURE USING(NUM_FACTURE) RIGHT JOIN VERSION USING(ID_VERSION) INNER JOIN EVENEMENT USING(ID_EVENT) INNER JOIN SALLE USING (NUM_SALLE) GROUP BY ID_VERSION HAVING VERSION.DATE > now() AND ID_VERSION != :ID";
 $anotherEvents = $conn->prepare($another);
 


 $login = "SELECT ID_UTILISATEUR, PASSWORD , USERNAME FROM UTILISATEUR";
 $sql = $conn->prepare($login);
 $sql->execute();
 $authentificationInfo = $sql->fetchALL(PDO::FETCH_ASSOC);

 $reserve = "SELECT * FROM EVENEMENT INNER JOIN VERSION USING(ID_EVENT) WHERE ID_VERSION = :ID";
 $details = $conn->prepare($reserve);

 $achats = "SELECT ID_UTILISATEUR, NOM, EMAIL, DATE_ACHAT, NUM_FACTURE AS NF, TITRE, TYPE, TARIF_REDUIT, TARIF_NORMAL,
 (SELECT COUNT(NUM_BILLET) FROM BILLET WHERE TYPE = 'normale' AND NUM_FACTURE = NF) AS NORMAL , 
 (SELECT COUNT(NUM_BILLET) FROM BILLET WHERE TYPE = 'reduite' AND NUM_FACTURE = NF) AS REDUITE,
 (SELECT NORMAL * TARIF_NORMAL + REDUITE * TARIF_REDUIT) AS TOTALE
 FROM EVENEMENT INNER JOIN VERSION USING(ID_EVENT) 
 INNER JOIN FACTURE USING(ID_VERSION)
 INNER JOIN BILLET USING (NUM_FACTURE) 
 INNER JOIN UTILISATEUR USING(ID_UTILISATEUR)
 GROUP BY NUM_FACTURE  HAVING ID_UTILISATEUR = :user;";
 $facture = $conn->prepare($achats);


?>